### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [BenasB/Orbur#1]
Hello, under what license is this project released under ? I would like to study it to learn from it. Thank you.

**Comment by benasb-bankera** [comment]
Hi, sorry I didn't receive a notification and didn't see that you opened this issue. Feel free to use this project however you want, this was built just as an exercise for me :D

**Comment by BenasB** [comment]
Hi, sorry I didn't receive a notification and didn't see that you opened this issue. Feel free to use this project however you want, this was built just as an exercise for me :D
